# ===============================
# Service configuration
# ===============================
spring.application.name=${SPRING_APPLICATION_NAME:USER-SERVICE}
server.port=${SERVER_PORT:8283}

# ===============================
# Eureka client configuration
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

# ===============================
# Database configuration
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/userservicedb}
spring.datasource.username=${DB_USERNAME:userservice}
spring.datasource.password=${DB_PASSWORD:S2011nppd}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=${FLYWAY_ENABLED:true}

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:VGhpc0lzQVN1cGVyU2VjdXJlMjU2Qml0S2V5MTIzNDU2}
jwt.expiration=${JWT_EXPIRATION:3600000}

# ===============================
# Kafka Producer Configuration
# ===============================
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=${KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
spring.kafka.producer.value-serializer=${KAFKA_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}

spring.kafka.producer.acks=${KAFKA_ACKS:all}
spring.kafka.producer.retries=${KAFKA_RETRIES:3}
spring.kafka.producer.properties.enable.idempotence=${KAFKA_IDEMPOTENCE:true}

# ===============================
# Kafka Topics
# ===============================
kafka.topic.user-created=${USER_CREATED_TOPIC:user-created-topic}